Repository FRONTENDBOOTCAMP-14th/Final-Project-Team-5, pull requests merged in 2025-10, with the labels that each got.

#23 feat. 이미지 업로드 폼 구현
  src/app/page.tsx
  src/components/ui/ImageForm.tsx
Labels: feature

#27 enhancement.Modal 애니메이션 추가작업
  src/components/ui/modal.tsx
Labels: enhancement

#31 feat. profile page 파일 생성
  src/app/profile/page.tsx
Labels: feature

#32 refactor. 알림창 다이얼로그 리팩토링
  src/app/page.tsx
  src/components/ui/Notification.tsx
Labels: refactor

#36 feat. 날씨 대시보드 컴포넌트 UI 구현
  public/weather/cloudy.svg
  public/weather/lightning.svg
  public/weather/rain.svg
  public/weather/snow.svg
  public/weather/sunny.svg
  src/app/page.tsx
  src/components/index.ts
  src/components/ui/WeatherDashboard.tsx
Labels: feature
